name: The Elementary MBA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3713
title: The Elementary MBA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73349047-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e7e8'
    - '#ef3b5f'
    - '#00a651'
    - '#babf32'
    - '#000000'
  brandStrength: 0.846967869438231
  lightness: 0.9375
  saturation: 0.06257861433550715
  rhythmicContrast: 0.5722833618056029
purpose: []
